name: market_space
flutter channel stablename: market_space
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:

  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^6.1.3
  provider: ^4.3.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  otp_text_field: ^1.1.2
  intl: ^0.16.1
  local_auth: 1.1.6
  fluro: "^1.6.3"
  flutter_rating_bar: 3.0.1+1
  image_picker: 0.8.4
  google_fonts: 2.0.0
  flutter_staggered_grid_view: "^0.3.2"
  flutter_svg: 0.21.0
  http: ^0.13.1
  meta: ^1.1.6
  equatable: ^1.0.0
  shared_preferences: 2.0.6
  flutter_secure_storage: ^3.3.5
  dio: 4.0.0
  rxdart: ^0.24.1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  google_sign_in: ^4.5.6
  lottie: 1.0.0
  fluttertoast: ^7.1.1
  cached_network_image: ^2.3.3
  crypto_font_icons: ^0.1.0+1
#  encrypt: ^4.1.0
  flutter_local_notifications: 5.0.0
  logger: ^0.9.4
  get_it: ^5.0.3
  file_picker: 4.0.0
  flutter_switch: ^0.2.0
  modal_bottom_sheet: ^1.0.0+1
#  emoji_picker: ^0.1.0
  video_player: ^2.2.0
  badges: ^1.1.6
  event_bus: ^1.1.1
  mockito: ^5.1.0
  custom_refresh_indicator: 0.9.0
  should_rebuild: 0.1.2
  photo_view: 0.4.0
  marquee: 1.6.1
  web_socket_channel: 2.1.0
  country_pickers: ^1.2.0
  sticky_headers: ^0.1.8
  animations: ^1.1.2
  flutter_staggered_animations: "0.1.3"
  carousel_slider: ^3.0.0
  firebase_storage: 10.0.0
  firebase_messaging: 10.0.0
  firebase_core: 1.4.0
  firebase_auth: 1.4.1
  cloud_firestore: 2.0.0
  flutter_fgbg : 0.0.1
#  cloud_firestore_mocks: 0.5.2+1
  webview_flutter: 1.0.7
  algolia: 1.0.1
  pull_to_refresh: 2.0.0
  shimmer: ^1.0.1
  flutter_lorem: 1.1.0
  flutter_image_compress: ^1.1.0
  image_size_getter: ^1.0.0
  sms_autofill: ^2.0.0
  pin_code_fields: ^7.3.0
  responsive_framework: ^0.1.4


  # sliver_tools: ^0.2.0

  
#  fl_chart: ^0.20.1


#  algolia:
#    git: https://github.com/kdy1/dart_algolia.git
#  algolia: ^0.1.6+1
#  native_video_view: ^0.3.0

#dependency_overrides:
#  intl: ^0.17.0-nullsafety.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.9.0

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  platform: ^3.1.0


flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/mkt_space_logo_ios.png"
  image_path_ios: "assets/images/mkt_space_logo_ios.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/images/
  - assets/images/financials/
  - assets/images/subcategories/
  - assets/loader/
  # - assets/images/subcategories/Her Accessories/
  # - assets/images/subcategories/His Accessories/
  - assets/images/subcategories/Men's Fashion/
  - assets/images/subcategories/Home & Kitchen/
  - assets/images/subcategories/Office/
  - assets/images/subcategories/Sports/
  - assets/images/subcategories/Technology/
  - assets/images/subcategories/Women's Fashion/
  - assets/images/subcategories/tech/
  - assets/images/subcategories/men_fashion/
  - assets/images/subcategories/home_kitchen/
  - assets/images/subcategories/her_a/
  - assets/images/subcategories/his_a/
  - assets/images/subcategories/women_fashion/
  - assets/images/svgs/
  - assets/jsons/


  fonts:
    - family: AppIcons
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family: inter
      fonts:
        - asset: assets/fonts/inter_black.ttf
        - asset: assets/fonts/inter_medium.ttf
        - asset: assets/fonts/inter_regular.ttf
        - asset: assets/fonts/inter_semibold.ttf
        - asset: assets/fonts/inter_bold.ttf
        - asset: assets/fonts/inter_light.ttf
        - asset: assets/fonts/inter_thin.ttf



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  main_locale: en_US
  enabled: true
